<?php

/** 
 * Implements hook_menu
 */
 
 function volunteertimeslots_menu() {
 	$items['vts-update'] = array(
            'title' => 'This is a callback function to update the schedule page',
            'description' => 'Callback function for the vts update page.',
            'page callback' => 'volunteertimeslots_ajax_callback',
            'theme callback' => 'ajax_base_page_theme', // Sets base theme to be the same as current page.
            'access arguments' => array('access content'),
            'type' => MENU_CALLBACK,
  );
  $items['vts-addslots/%'] = array(
    'title' => '',
    'description' => 'Callback function for the vts add slots page.',
    'page callback' => 'vts_addslots',
    'page arguments' => array(1),
    'access arguments' => array('administer slots'),
    'type' => MENU_CALLBACK,
  ); 
  $items['zap'] = array(
    'title' => 'This is function to zero the session variable',
    'description' => 'Zap the session variable.',
    'page callback' => 'volunteertimeslots_zapsession',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['vtsintervals'] = array(
    'title' => 'A demonstration of the vtsentity module',
    'page callback' => 'vtsentity_vtsintervals',
    'file' => 'vtsentity.info.inc',
    'file path' => drupal_get_path('module', 'volunteertimeslots') . '/includes',
    'access arguments' => array('access content'),
  );
  
  $items['vtsinterval/%'] = array(
    'title' => 'VTSInterval',
    'page callback' => 'vtsentity_view_vtsinterval',
    'file' => 'includes/vtsentity.info.inc',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
 	return $items;
 }
 
 /**
 *	Implements hook_permission
 */
 
function volunteertimeslots_permission () {
 	return array (
 		'administer slots' => array (
 			'add slots' => t('Add time slot elements'),
 			'description' => t('Add time slot elements to the data array'),
 		), 
 	);
 }
 /*
  *     Implements hook_views_api
  */
function volunteertimeslots_views_api() {
    return array(
        'api' => 3,
        'path' => drupal_get_path('module','volunteertimeslots') . '/views',
    );
}
  function volunteertimeslots_views_pre_render(&$view) {
        $a = 1;
        if ($view->name == 'vtsdailyview') {        
            drupal_add_js('misc/ajax.js');
            drupal_add_css(drupal_get_path('module','volunteertimeslots') . '/css/volunteertimeslots.css');
            $myentity = entity_load('vtsinterval');
            /*  This foreach loop is a crude way to accomplish what
             *  I'm trying to do, which is get the EventID for this day.
             *  I need the EventID so that I can route viewers to the
             *  correct event in the link below the daily schedule.  Entities
             *  have an EntityFieldQuery method that I should use to get
             *  this information instead of just spinning through all vtsinterval
             *  entities until I find one with the right day.  However,
             *  I didn't want to take the time to learn how to use this method
             *  so I just implemented this loop.
             */
            foreach ($myentity as $interval ){
                if ($interval->EventDay == $view->args[0]) {
                    $EventID = $interval->EventID;
                    break;
                }
            }
        $view->attachment_after = '<span><h2>' . l('Sign up for a different day', 'vtsviews/' . $EventID, array('attributes' => array('class' => 'otherdays')));
        $view->attachment_after .=  l('Look at other events', 'vtsvolunteerevents/', array('attributes' => array('class' => 'otherevents'))) . '</h2></span>';

        }
    if ($view->name == 'vtseventday') {
        $topstuff = vts_dailyheader($view->args[0], $view);
        $view->attachment_before = $topstuff['connect'];
        $view->attachment_after = $topstuff['nickname'];
    }
  }
  /*
   *    A helper routine to create the html that will be displayed in the header of
   *    the vtsdailyview view
   */
    function vts_dailyheader($day, $view) {
        global $user;
        global $base_url;
        if (isset($_SESSION['vtsusrobj'])) {
            $vtsusrobj = $_SESSION['vtsusrobj'];
//            $query = 'SELECT * FROM {gopuser} WHERE email LIKE ' . 'CONCAT(\'a@mic4l.com\'' . ',\'%\')';
            $query = 'SELECT * FROM {gopuser} WHERE email LIKE ' . 'CONCAT(\'' . $vtsusrobj->email . '\',\'%\') ';
            $b = 1;
            if ( ($vtsusrobj->email != '') && ( $vtsusrobj->handle == '' ) )
                {
                    $result = db_query($query,array(':usremail' => $vtsusrobj->email));
                    if ($record = $result->fetchObject()) {
			$vtsusrobj->handle = $record->handle;
                    }
                }               
        }
        /*
         *  If we did not have a vtsusrobj then we now
         *  construct one.  Note that the email address here
         *  is the one found in the gopuser table.  If
         *  this is an anonymous user coming here for the first
         *  time, we will ask for the email in the Connect link.
         *  On subsequent returns to this code, the user will
         *  have provided an e-mail and it will have been stored
         *  in the vtsuserobj.
         * 
         *  The reason we're doing it this way is to make it possible
         *  for users to use the volunteer time slot system without
         *  logging in to our site.
         */
	if ( !isset($vtsusrobj) ) {
 		$vtsusrobj = new stdClass();
                $query = 'SELECT * FROM {gopuser} WHERE email LIKE ' . 'CONCAT(\'' . $user->mail . '\',\'%\') ';
                $record = new stdClass();
                $vtsusrobj->dayid = $day;
                $result = db_query($query);
                if ($user->mail != '') {
                    if ($record = $result->fetchObject()) {
			$vtsusrobj->email = $user->mail;
			$vtsusrobj->handle = $record->handle;
                    }
		}
 	  $_SESSION['vtsusrobj']= $vtsusrobj;

            }
            $vtstoplinks = array();
            
         /*
          *     Create the Connect (or Disconnect) link
          */
            $vtshdr = '<div class=vtstoplink>';
            if ($vtsusrobj->handle != '') {
                $vtshdr .= '<a href=' . $base_url . '/zap>Disconnect</a></div';
            } elseif ($vtsusrobj->email != '') {
                $gourl = popup_forms_link('vtspopups_nickname_form',t('Connect'));
                $vtshdr .= $gourl . '</div>';
            } else {
                $gourl = popup_forms_link('vtspopups_login_form',t('Connect'));
                $vtshdr .= $gourl . '</div>';
            }
            $vtsnickname = '<div class = vtstopnickname>';
            if ( $vtsusrobj->handle != ''){
                $vtsnickname .= 'Nickname:   ' . $vtsusrobj->handle . '</div>';
            } else {
                $vtsnickname .= 'You need to tell us who you are before you can volunteer. <p> Please click on the Connect link to sign in to the system.</p>';
            }
            $vtstoplinks['connect'] = $vtshdr;
            $vtstoplinks['nickname'] = $vtsnickname;

            return $vtstoplinks;
        
    }

/**
*		This little stub of a function just returns the current users handle
*/
function volunteertimeslots_ajax_callback($type='ajax')  {
		if ($type == "nojs") {
		$output = "Javascript is not running";
		return $output;
		}
                drupal_add_js('misc/ajax.js');
		global $user;
                global $base_url;
                if (!isset($vtsusrobj))
                    $vtsusrobj = $_SESSION['vtsusrobj'];

		$usrHandle = $vtsusrobj->handle;
		$itemID = $_GET[itemID];
                $itemslot = $_GET[itemslot];
                
                $myentity = entity_load('vtsinterval',array($itemID));
                $myupdateentity = $myentity[$itemID];
                $itemHandle = $myupdateentity->{'handle' . $itemslot};
                
		$rplHandle = vts_getReplacementHandle($usrHandle,$itemHandle, $vtsusrobj);  //The value of the new handle
              
                $myupdateentity->{'handle' . $itemslot} = $rplHandle;
                $myupdateentity->save();
                
                $commands = array();
		$commands[] = ajax_command_html('.vtsclass' . $itemID . '_' . $itemslot, $rplHandle);
		$page = array('#type' => 'ajax', '#commands' => $commands);
		ajax_deliver($page);
}
function vts_addslots($arg1) {
	$node = node_load($arg1);
	$output = '';
		$eventIDarr = field_get_items('node',$node,'field_vtsevent');
		$eventID = $eventIDarr[0]['target_id'];
	 	$startTimearr = field_get_items('node',$node,'field_vtsstarttime');
		$startTime = $startTimearr[0]['value'];
	 	$endTimearr = field_get_items('node',$node,'field_vtsendtime');
		$endTime = $endTimearr[0]['value'];
	 	$numVolSlotsarr = field_get_items('node',$node,'field_vtsslots');
	 	$numVolSlots = $numVolSlotsarr[0]['value'];
	 	$slotTimeIntervalarr = field_get_items('node',$node,'field_vtsinterval');
	 	$slotTimeInterval = $slotTimeIntervalarr[0]['value'];
		$output	= '<br><h2>I am in the addslots routine with an argument of ' . $arg1;
		$output .= '<br>The event is ' .  $eventID;
		$output .= '<br>The start time is:  ' . $startTime;
		$output .= '<br>The end time is ' . $endTime;
		$output .= '<br>The number of slots is ' . $numVolSlots;
		$output .= '<br>The slot interval is: ' . $slotTimeInterval;

        for ($time = $startTime; $time < $endTime; $time = $time + 60*$slotTimeInterval) {
            $myentity = entity_create('vtsinterval',array());
            $myentity->timestart = $time;
            $myentity->timeend = $time + 60*$slotTimeInterval;
            $myentity->EventID = $eventID;
            $myentity->EventDay = $arg1;
            for ($j = 1; $j < $numVolSlots + 1; $j++){
                $myentity->{"handle" . $j} = "Open";       
           }
            $myentity->save();
        }
//	for ($time = $startTime; $time < $endTime ; $time = $time + 60*$slotTimeInterval) {
	
	
//		$slotstart = $time;
//		$slotend = $time + $slotTimeInterval * 60;

//		for($volslot=1; $volslot <= $numVolSlots; $volslot++) {

//                    $tblrow = db_insert('volunteertimeslots_slotdata')
//			->fields(array(
//					'slotstart' => $slotstart,
//					'slotend' => $slotend,
//					'eventID' => $eventID,
//					'eventDay' => $arg1,
//					'vsnumber' => $volslot,
//					'handle' => 'Open',
//					))
//				->execute();
//
//			$output .= '<br>'. $eventID . ' ' . $arg1 .' ' .' ' . $slotstart . ' ' . $slotend . ' ' . $volslot. ' ' . 'Open';
//				$output .= '<br> The table insert row is ' . $tblrow;
//		}

//	}
	
return render($output);

}
function getvtsusrcreds($user, &$vtsusrobj) {
	if ($user->uid != 0 ) {
	$vtsusrobj->email = $user->mail;	
	$result = db_query("
		SELECT * FROM {gopuser}
		WHERE email LIKE CONCAT(:usremail,'%')" ,
		array(':usremail' => $user->mail));
		if ($record = $result->fetchObject()) {
			$vtsusrobj->email = $user->mail;
			$vtsusrobj->handle = $record->handle;
		}
	} else {
	
	/*		This is the anonymous user case
	
	
	*/
	if ($vtsusrobj->email != "") {       //Has user entered an email?

			$matchvalue = $vtsusrobj->email;
		 $result = db_query("
			SELECT * FROM {gopuser}
			WHERE email LIKE CONCAT(:usremail,'%')",
			array('usremail' => $matchvalue));
			if ($record = $result->fetchObject()) {
					$vtsusrobj->email = $record->email;
					$vtsusrobj->handle = $record->handle;
			} else {
					$vtsusrobj->sessionstart = '3333333';			//This is, for now, the match failed indicator
					drupal_goto('BV');
					die;

			}		
}
return;	
}
}
function setvtsusrcreds($user,&$vtsuser)  {
global $user;

/*		
		First check to see if this Nickname has been used before
		(For now, just return if it has)
*/		
$result = db_query("
		SELECT * FROM {gopuser}
		WHERE handle = :hdl ",
		array(':hdl' => $vtsuser->handle));
		

if ($result->fetchObject()) {
	$vtsuser->invalidnickname = TRUE;
	return;	
}
$numupdated = db_update('gopuser')
		->fields(array(
			'handle' => $vtsuser->handle,
                            )
                        )
		->where("email LIKE CONCAT(:usremail, '%')",
			array(':usremail' => $vtsuser->email))
		->execute();
		

return;
}

/**
*			This routine returns the new handle for the time slot that the user
*			clicked on.  $usrHandle is the user's handle, $handle is what is already
*			there.
*/

function vts_getReplacementHandle($usrHandle, $handle, &$vtsusrobj) {
	$a = 1;
	if ($usrHandle == '') {
		return $handle;		// If usrHandle is null, make no change	
	}
	if ($handle == 'Open') {
		return $usrHandle;
	}
	if ($handle == $usrHandle) {
		return 'Open';		// Clicking on a handle we have already selected should unvolunteer us
	} else {
		return $handle;		// Cannot change somebody else's handle	
	}
}
function volunteertimeslots_zapsession()  {
global $base_url;
		$_SESSION = array();
//		session_destroy();
		cache_clear_all(NULL,'cache_page');
		drupal_goto('<front>');
}
/*
 *  Implements hook_login.  Eliminate any session variable
 *  that might be hanging around when a user logs in.  This 
 *  prevents an incomplete vtsusrobj from remaining in the
 *  system and being used when another user logs in on the
 *  same session.
 */
function volunteertimeslots_user_login () {
    $_SESSION = array();
    cache_clear_all(NULL, 'cache_page');
            
}
/*
*		Implments hook_form_alter
*/
function vtspopups_form_alter(&$form, &$form_state, $form_id) {
	
	if( $form_id == "vtspopups_nickname_form") {
			$vtsuser = $_SESSION['vtsusrobj'];
			if ($vtsuser->invalidnickname ) {
			   $form['arg']['#title'] = 'We are sorry, but that nickname has already been taken.  Please choose another one';	
		  }
	}
}
/**
 * Implements hook_entity_info() for the entity [vtsinterval]
 * that is used by the volunteertimeslots moldule.
 */
    function volunteertimeslots_entity_info() {
      $info = array();
      $info['vtsinterval'] = array(
        'label' => t('VTSinterval'),
        'access arguments' => array('administer users'),
        'label callback' => 'vtsentity_label_callback',
        'base table' => 'vtsentity_vtsintervals',
        'entity keys' => array(
          'id' => 'id',
          'label' => 'id', 
        ),
        'entity class' => 'vtsintervalEntity',
        'controller class' => 'vtsintervalEntityController',
        'access callback' => 'vtsentity_access_callback',
        'uri callback' => 'entity_class_uri',
//    'admin ui' => array(
//      'path' => 'admin/vtsintervals',
//      'controller class' => 'EntityDefaultUIController',
//        ),
        'fieldable' => TRUE,
        'bundles' => array(
          'vtsinterval' => array(
            'label' => t('vtsinterval'),
//            'admin' => array(
//            'path' => 'admin/vtsintervals',
//            ),
          ),
        ),
        'views controller class' => 'EntityDefaultViewsController',
        'module' => 'volunteertimeslots',
        );
      
      return $info;
}

/**
 * Implements hook_entity_property_info() for the entity [vtsinterval]
 * that is used by the volunteertimeslots module.
 */
    function volunteertimeslots_entity_property_info() {
        
      $info = array();
      
      $info['vtsinterval']['properties']['EntityID'] = array(
        'name' => 'EntityID',
        'label' => t('VTSInterval ID'),
        'description' => t('The ID of the VTSInterval.'),
        'type' => 'integer',
        'schema field' => 'id',
      );
      
      $info['vtsinterval']['properties']['EventID'] = array(
        'label' => t('EventID'),
        'description' => t('The event to which this interval is attached'),
        'type' => 'node',
        'bundle' => 'voluntertimeslotevent',
        'schema field' => 'EventID',
      );
      $info['vtsinterval']['properties']['EventDay'] = array(
        'label' => t('EventDay'),
        'description' => t('The day to which this interval is attached'),
        'type' => 'integer',
        'schema field' => 'EventDay',
      );
      $info['vtsinterval']['properties']['timestart'] = array(
        'label' => t('Start Time'),
        'description' => t('The start time for this interval'),
        'type' => 'date',
        '[granularity][month]' => 'month',
        '[granularity][day]' => 'day',
        '[granularity][hour]' => 'hour',
         '[granularity][minute]' => 'minute',
         '[granularity][year]' => 'year',
        'schema field' => 'timestart',
      );
      $info['vtsinterval']['properties']['timeend'] = array (
         'label' => t('End Time'),
         'description' => t('The end time for this interval'),
         'type' => 'date',
         'schema field' => 'timeend',
      );
      $info['vtsinterval']['properties']['handle1'] = array (
          'label' => t('handle1'),
          'description' => t('The first handle'),
          'type' => 'text',
          'schema field' => 'handle1'
      );
      $info['vtsinterval']['properties']['handle2'] = array (
          'label' => t('handle2'),
          'description' => t('The second handle'),
          'type' => 'text',
          'schema field' => 'handle2'
      );
      $info['vtsinterval']['properties']['handle3'] = array (
          'label' => t('handle3'),
          'description' => t('The third handle'),
          'type' => 'text',
          'schema field' => 'handle3'
      );
      $info['vtsinterval']['properties']['handle4'] = array (
          'label' => t('handle4'),
          'description' => t('The fourth handle'),
          'type' => 'text',
          'schema field' => 'handle4'
      );
      $info['vtsinterval']['properties']['handle5'] = array (
          'label' => t('handle5'),
          'description' => t('The fifth handle'),
          'type' => 'text',
          'schema field' => 'handle5'
      );
      
      return $info;
}